version: 2
defaults:
  checks_failure_payload: &checks_failure_payload
    title: 'Mergeable Run have been Completed!'
    summary: '### Status: {{toUpperCase validationStatus}}
              Here are some stats of the run:
              {{validationCount}} validations were ran.
              {{passCount}} PASSED
              {{failCount}} FAILED'
    text: '{{#each validationSuites}}\n
          #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
          {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                  Input : {{{details.input}}}\n
                  Settings : {{{displaySettings details.settings}}}\n
                  {{/each}}\n
          {{/each}}'
          
mergeable:
  - when: pull_request.*
    name: 'WIP Title Check'
    validate:
      - do: title
        # Do not merge when it is marked work in progress (WIP)
        must_exclude:
          regex: \[WIP\]|\bWIP\b|🚧
          message: This is work in progress. Do not merge yet.
  - when: pull_request.*
    name: 'Empty Description Check'
    validate:
      - do: description
        no_empty:
          # Do not allow empty descriptions on PR.
          enabled: true
          message: 'Description can not be empty.'
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
        leave_old_comment: false
      - do: comment
        payload:
          body: 'Description is necessary and should not be empty. Kindly provide details with **what** was changed, **why** it was changed, and **how** it was changed.'
