version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        # Do not merge when it is marked work in progress (WIP)
        must_exclude:
          regex: \[WIP\]|\bWIP\b|🚧
          message: This is work in progress. Do not merge yet.

      # Do not allow 'DO NOT MERGE' phrase on PR's description.
      - do: description
        must_exclude:
          # Do not allow 'DO NOT MERGE' phrase on PR's description.
          regex: 'DO NOT MERGE'
          message: 'Description says that the PR should not be merged yet.'
        no_empty:
          # Do not allow empty descriptions on PR.
          enabled: true
          message: 'Description can not be empty.'

       # Do not allow PR with label 'PR: work in progress'                
      - do: label
        must_exclude:
          regex: 'progress|do-not-merge|wip'     
          message: 'This PR is flagged as a work in progress.'
      - do: label
        must_exclude:
          regex: 'feedback'     
          message: 'This PR is flagged as waiting for feedback.'          
      - do: label
        must_exclude:
          regex: 'duplicate'        
          message: 'This PR is flagged as a duplicate.'
      - do: label
        must_exclude:
          regex: 'invalid'        
          message: 'This PR is flagged as a invalid.'                      
      - do: label
        message: Must be labeled `ok-to-merge`
        must_include:
          regex: 'ok-to-merge'
      - do: label
        no_empty:
          message: PR needs to be labeled
          enabled: true
        
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'Labels are not satisfied'
          summary: 'PR needs to be labeled `ok-to-merge`'

  - when: pull_request.*
    validate:
    - do: description
      no_empty:
        enabled: true
        message: |
          Description should not be empty. Provide details with **what** was changed, **why** it was changed, and **how** it was changed.

    - do: dependent
      files: ['README.md', 'README.yaml']
      message: README.md and README.yaml must be updated together

    # If package.json is updated, so should yarn.lock
    - do: dependent
      changed:
        file: 'README.yaml'
        files: ['README.md']
        
#    - do: dependent
#      changed:
#        file: '*'
#        files: ['CHANGELOG.md']
#        message: Missing CHANGELOG entry