# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github
repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: test
  # A short description of the repository that will show up on GitHub
  description: "\U0001F3D7️ Used as a sandbox for testing. Do not use."
  # A URL with more information about the repository
  homepage: https://cloudposse.com
  # A comma-separated list of topics to set on the repository
  topics: test, sandbox
  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: false
  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false
  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false
