name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  deployments: write
  
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    concurrency: release
    steps:
      - uses: cloudposse/github-action-major-release-tagger@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY.PRIVATE_KEY }}
      - uses: cloudposse/github-action-release-branch-manager@v1
        env:
          GITHUB_TOKEN: ${{ steps.github-app.outputs.token }}