name: Scheduled Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/scheduled.yml"

permissions:
  pull-requests: write
  contents: read

jobs:
  scaffolding:
    if: startsWith(github.head_ref, 'security/') || startsWith(github.head_ref, 'auto-update/') || startsWith(github.head_ref, 'dependabot/') || startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    environment: security
    steps:
      - name: Run organizational action
        uses: cloudposse-github-actions/.github@repo-scaffolding
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
