name: Scheduled Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - 'security/**'
      - 'auto-update/**'
      - 'dependabot/**'
      - 'renovate/**'
    paths:
      - ".github/workflows/scheduled.yml"

permissions:
  pull-requests: write
  contents: read

jobs:
  scaffolding:
    runs-on: ubuntu-latest
    environment: security
    steps:
      - name: Run organizational action
        uses: cloudposse-github-actions/.github@repo-scaffolding
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
